# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64540a323aa5ded4955a935b93a05dc03aaa851ee267a05d0a9f9fe20ccd4ec53bba5327e377f56e9c8c43d635c75430ccff0e22428abb1a998f7405218035af

test:
  secret_key_base: f0cf28d09e4549e8709651b54408a1d1e076a3c937dd39f1ef5fc41fc8545643ae666bf7c9edc0a845748a2582a72e7dc21892e0935971c6a1b33cdd8fc2d8b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
